apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-certificate
  namespace: istio-system
spec:
  secretName: httpbin-certificate
  subject:
    organizations:
      - stenlund
  commonName: httpbin.home
  dnsNames:
  - httpbin.home
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io