apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-certificate
  namespace: istio-system
spec:
  secretName: longhorn-certificate
  subject:
    organizations:
      - stenlund
  commonName: longhorn.home
  dnsNames:
  - longhorn.home
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
