apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fjdb
  namespace: forgejo
spec:

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      encoding: UTF8
      localeCollate: en_US.UTF-8
      localeCType: en_US.UTF-8
      secret:
        name: fjdb-secret

  instances: 3
  storage:
    storageClass: longhorn
    size: 2Gi

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: digitalocean-store