apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-claim
  namespace: forgejo
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

