apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: tomas.stenlund@telia.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-staging-issuer-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: http-01-acme-gateway
              namespace: istio-system
              kind: Gateway


